apiVersion: v1
kind: Secret
metadata:
  name: gke5b-kubeconfig
  namespace: kargo-helm-prom-stack
  labels:
    kargo.akuity.io/cred-type: generic

stringData:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: <removed>
        server: https://<removed>
      name: gke_sdwssgl-saas-gke5_us-west1_sdwssgl-saas-gke5b
    contexts:
    - context:
        cluster: gke_sdwssgl-saas-gke5_us-west1_sdwssgl-saas-gke5b
        namespace: sedwsskestrel-kps1-dgcamo
        user: gke_sdwssgl-saas-gke5_us-west1_sdwssgl-saas-gke5b
      name: gke_sdwssgl-saas-gke5_us-west1_sdwssgl-saas-gke5b
    current-context: gke_sdwssgl-saas-gke5_us-west1_sdwssgl-saas-gke5b
    kind: Config
    preferences: {}
    users:
    - name: gke_sdwssgl-saas-gke5_us-west1_sdwssgl-saas-gke5b
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1beta1
          args: null
          command: gke-gcloud-auth-plugin
          env: null
          installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
            https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
          interactiveMode: IfAvailable
          provideClusterInfo: true
