apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm-prom-stack
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/cloud-hacks/kargo-helm-prom-stack.git
      revision: HEAD
      directories:
      - path: kube-prometheus-stack/env/test
  template:
    metadata:
      name: 'kube-prometheus-stack-test'
      annotations:
        kargo.akuity.io/authorized-stage: 'kargo-helm-prom-stack:test'
    spec:
      destination:
        namespace: monitoring
        name: 'test'
      project: kargo-helm
      source:
        repoURL: https://github.com/cloud-hacks/kargo-helm-prom-stack.git
        targetRevision: 'env/test'
        path: .
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
