apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-prom-stack
spec:
  project: kargo-helm
  source:
    repoURL: https://github.com/cloud-hacks/kargo-helm-prom-stack.git
    path: kargo
  destination:
    name: kargo1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    
